- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: update pacman
      become: yes
      pacman: 
        update_cache: yes
        upgrade: yes
  tasks:
    - name: make user
      user:
        name: "bastiaan"
        state: present
        shell: /bin/zsh
        createhome: yes
        home: "/home/bastiaan"
        groups: wheel
        append: yes

    - name: Installing packages
      become: yes
      pacman: 
        name:
          # - code
          - ttf-meslo-nerd
          - alacritty
          - keepassxc
      tags: &tags [ 'install' ]

    - import_tasks: tasks/ssh.yml
      tags: [ 'required' ]
    - import_tasks: tasks/git.yml
      tags: [ 'required' ]
    - import_tasks: tasks/zsh.yml
      tags: [ 'required' ]
    - import_tasks: tasks/dotfiles.yml
      tags: [ 'required' ]
    - import_tasks: tasks/nvm.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/borg.yml

