- name: Installing stow
  pacman: 
    name:
      - stow
  tags: &tags [ 'install', 'stow', 'dotfiles' ]

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:tionkje/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: stow
  tags: *tags

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./archlinux.sh
  tags: *tags
