- name: Install openssh
  become: yes
  pacman: 
    name: 
      - openssh
  tags: &tags [ 'install', 'ssh', 'dotfiles' ]

- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  become: true
  become_user: bastiaan
  tags: *tags
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  become: true
  become_user: bastiaan
  tags: *tags
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  become: true
  become_user: bastiaan
  tags: *tags
# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
#   with_fileglob:
#   - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
