- name: Install zsh
  pacman: 
    name: 
      - zsh
      - which
      - curl
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
- name: install antibody
  shell: curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
